// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO7tXwMjcHb2MdUyEyPWTOpHKFHCBkcBQ',
    appId: '1:1041604752171:web:c5eebeb48761556976cb6e',
    messagingSenderId: '1041604752171',
    projectId: 'global-chat-demo',
    authDomain: 'global-chat-demo.firebaseapp.com',
    storageBucket: 'global-chat-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHJ_uwmDO-XcwQphEVtyhIjfBFHRcqJXU',
    appId: '1:1041604752171:android:66a2a2080d09ca4e76cb6e',
    messagingSenderId: '1041604752171',
    projectId: 'global-chat-demo',
    storageBucket: 'global-chat-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU-2--SJvD9xR_1gka6Y8KbgEDQJ6w1-o',
    appId: '1:1041604752171:ios:35dfa741112c87a076cb6e',
    messagingSenderId: '1041604752171',
    projectId: 'global-chat-demo',
    storageBucket: 'global-chat-demo.firebasestorage.app',
    iosBundleId: 'com.example.shakuniyaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU-2--SJvD9xR_1gka6Y8KbgEDQJ6w1-o',
    appId: '1:1041604752171:ios:35dfa741112c87a076cb6e',
    messagingSenderId: '1041604752171',
    projectId: 'global-chat-demo',
    storageBucket: 'global-chat-demo.firebasestorage.app',
    iosBundleId: 'com.example.shakuniyaTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO7tXwMjcHb2MdUyEyPWTOpHKFHCBkcBQ',
    appId: '1:1041604752171:web:4b84c9181bee19b676cb6e',
    messagingSenderId: '1041604752171',
    projectId: 'global-chat-demo',
    authDomain: 'global-chat-demo.firebaseapp.com',
    storageBucket: 'global-chat-demo.firebasestorage.app',
  );
}
